model:
  input_shape: [224, 224, 3]
  num_classes: 90  # Number of object classes
  backbone: "mobilenetv2"
  
data:
  train_path: "data/train"
  val_path: "data/val"
  batch_size: 32
  prefetch_size: 4
  
augmentation:
  random_flip: true
  random_rotation: 15  # degrees
  random_brightness: 0.2
  random_contrast: 0.2
  random_hue: 0.1
  
training:
  learning_rate: 0.001
  epochs: 100
  box_loss_weight: 1.0
  checkpoint_frequency: 5
  checkpoint_dir: "checkpoints"
  early_stopping_patience: 10
  
callbacks:
  tensorboard:
    log_dir: "logs"
  model_checkpoint:
    monitor: "val_loss"
    save_best_only: true
  
evaluation:
  iou_threshold: 0.5
  score_threshold: 0.3